# -*- coding: utf-8 -*-
"""Generate_JinaAI_Embeddings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yAIiamgNXRcX9B2dN-j2lIAsxMCWq_c2
"""

import os
import pandas as pd
import math

!pip install openpyxl

import certifi
import json
import requests

from google.colab import drive

folder_path = '/content/drive/My Drive/startup'
files = os.listdir(folder_path)
print(files)

df = pd.read_csv('/content/drive/My Drive/startup/startup_ticker_file.csv', encoding='latin-1')

second_column_df.to_csv('/content/drive/My Drive/startup/startups.csv', index=False)

def get_embeddings(ex_list):

  url = 'https://api.jina.ai/v1/embeddings'

  headers = {
  'Content-Type': 'application/json',
  'Authorization': 'Bearer JINA API key'
  }
  data = {
      'input': [*ex_list],
      'model': 'jina-embeddings-v2-base-en'
      }
  response = requests.post(url, headers=headers, json=data)
  data = response.json()
  print(data)
  num_rows = len(data['data'])
  df = pd.DataFrame(index=range(num_rows), columns=['Embeddings'])
  for i in range(len(df)):
    df.at[i, 'Embeddings'] = data['data'][i]['embedding']

  return df

import pandas as pd

# Replace with your file path
file_path = '/content/drive/My Drive/startup/name_description.txt'

# Read the .txt file line by line and split by the first comma
with open(file_path, 'r') as file:
    lines = file.readlines()

# Split each line by the first comma
data = [line.strip().split(',', 1) for line in lines]

# Convert the result to a DataFrame
df_new = pd.DataFrame(data)

# Display the first few rows of the DataFrame
print(df_new)

df_new.columns = [None] * len(df_new.columns)

# Display the DataFrame without column names
df_new.head()

df_new.columns = ['Startup Name', 'Description']

df_new = df_new.drop(index=0)

columns = ['Startup Name', 'Description']
resulting_df = pd.DataFrame(columns=columns)

ex = df_new['Description']
ex_list = ex.to_list()
df = get_embeddings(ex_list)
df_joined = df.join(df_new)
resulting_df = pd.concat([resulting_df, df_joined], ignore_index=True)

resulting_df.to_csv('/content/drive/My Drive/startup/startups_embeddings.csv', index=False)

"""# New Section"""

file_path = '/content/drive/My Drive/startup/data_crunch.csv'

# Read the Excel file into a DataFrame
df_crunch = pd.read_csv(file_path, encoding='latin-1')

# Display the first few rows of the DataFrame
print(df_crunch.head())

new_df.to_csv('/content/drive/My Drive/startup/data_crunch_description.csv', index=False)

df_crunch = pd.read_csv('/content/drive/My Drive/startup/data_crunch_description.csv', encoding='latin-1')

print(df_crunch)

df_range = df_crunch.iloc[8000:10000]

df_reset = df_range.reset_index(drop=True)

print(df_reset)

print(resulting_crunch_df_10000)

columns_crunch = ['name', 'short_description']
resulting_crunch_df_10000 = pd.DataFrame(columns=columns_crunch)

ex_crunch = df_range['short_description']
ex_crunch_list = ex_crunch.to_list()
df_crunch_embeddings = get_embeddings(ex_crunch_list)
df_crunch_joined = df_reset.join(df_crunch_embeddings)

print(df_crunch_joined)

df_joined = df.join(df_new)
resulting_df = pd.concat([resulting_df, df_joined], ignore_index=True)

print(df_crunch_joined)

print(resulting_crunch_df_4000)

chunk_size = 1000

# Split the DataFrame into chunks and process each chunk
for start in range(0, len(df_crunch), chunk_size):
    end = start + chunk_size
    chunk = df_crunch.iloc[start:end]  # Select chunk of 2000 rows

    # Extract the 'short_description' column and get embeddings
    ex_crunch_list = chunk['short_description'].tolist()
    chunk_embeddings = get_embeddings(ex_crunch_list)

    # Convert the embeddings to a DataFrame
    chunk_embeddings_df = pd.DataFrame(chunk_embeddings)

    # Join the embeddings with the original chunk
    df_crunch_joined = chunk.join(chunk_embeddings_df)

    # Concatenate the chunk result to the final resulting DataFrame
    resulting_crunch_df = pd.concat([resulting_crunch_df, df_crunch_joined], ignore_index=True)

# Check the final DataFrame
print(resulting_crunch_df.head())  # Print first few rows to check the result

df_crunch_joined.to_csv('/content/drive/My Drive/startup/data_crunch_allfields_embeddings_10000.csv', index=False)

print(resulting_crunch_df_2000)

"""# New Section"""

print(ex_crunch)

import pandas as pd

# List of your CSV file paths (in the desired order)
csv_files = ['/content/drive/My Drive/startup/data_crunch_allfields_embeddings_2000.csv', '/content/drive/My Drive/startup/data_crunch_allfields_embeddings_4000.csv', '/content/drive/My Drive/startup/data_crunch_allfields_embeddings_6000.csv', '/content/drive/My Drive/startup/data_crunch_allfields_embeddings_8000.csv', '/content/drive/My Drive/startup/data_crunch_allfields_embeddings_10000.csv']

# Read and append them into one DataFrame
combined_df = pd.concat([pd.read_csv(file) for file in csv_files], ignore_index=True)

# Optional: save to a new CSV
combined_df.to_csv('/content/drive/My Drive/startup/combined_output.csv', index=False)

print("All CSVs combined successfully!")

